# Generated by Django 6.0.5 on 2026-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this AI agent', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What does this agent do?')),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant.', help_text='Hidden instructions sent to the AI every time')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='Which AI model to use (e.g., gpt-4o-mini, claude-3-haiku)', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level: 0 = robotic, 2 = chaotic')),
                ('max_tokens', models.IntegerField(default=512, help_text='Maximum response length in tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Is this agent currently available?')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
