# Generated by Django 6.0.5 on 2026-06-03 10:55

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('role', models.CharField(choices=[('support', 'Customer Support'), ('sales', 'Sales Assistant'), ('technical', 'Technical Support')], default='support', max_length=20)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this AI agent', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What does this agent do?')),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant.', help_text='Hidden instructions sent to the AI every time')),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='Which AI model to use (e.g., gpt-4o-mini, claude-3-haiku)', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level: 0 = robotic, 2 = chaotic')),
                ('max_tokens', models.IntegerField(default=512, help_text='Maximum response length in tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Is this agent currently available?')),
                ('owner', models.ForeignKey(help_text='The user who owns this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System'), ('tool', 'Tool Result')], default='user', max_length=20)),
                ('content', models.TextField(help_text='The actual message text')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info: model used, tokens consumed, tools called, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='Which agent this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agent')),
                ('user', models.ForeignKey(help_text='Which human user sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='AI-generated meaning coordinates for semantic search', null=True)),
                ('agent', models.ForeignKey(help_text='The agent this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agents.document')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='document_embedding_ivfflat_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
