# Generated by Django 6.0.5 on 2026-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('support', 'Customer Support'), ('sales', 'Sales Assistant'), ('technical', 'Technical Support')], default='support', max_length=20),
        ),
    ]
