# Generated by Django 6.0.5 on 2026-06-02 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System'), ('tool', 'Tool Result')], default='user', max_length=20)),
                ('content', models.TextField(help_text='The actual message text')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info: model used, tokens consumed, tools called, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='Which agent this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agent')),
                ('user', models.ForeignKey(help_text='Which human user sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
