# Generated by Django 6.0.5 on 2026-06-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='agent',
            field=models.ForeignKey(help_text='The agent this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent'),
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
