# Generated by Django 6.0.5 on 2026-06-01 16:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_document_options_agent_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='AI-generated meaning coordinates for semantic search', null=True),
        ),
    ]
