# Generated by Django 6.0.5 on 2026-06-01 17:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_document_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Which AI model to use (e.g., gpt-4o-mini, claude-3-haiku)', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='AI-generated meaning coordinates for semantic search', null=True),
        ),
    ]
